version: '3.6'
services:
  gitlab:
    image: gitlab-ee-local:15.10.7-ee.0
    restart: always
    hostname: 'gitlab.green-rabbit.net'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.green-rabbit.net"
        registry_external_url "http://registry.green-rabbit.net:5000"

        letsencrypt['enable'] = false
        
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
       
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.gmail.com'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = 'XXXX@gmail.com'
        gitlab_rails['smtp_password'] = 'XXXXXX'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'gitlab@green-rabbit.net'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab'
        
        nginx['enable'] = true
        nginx['listen_port'] = 443
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate']     = "/etc/gitlab/ssl/gitlab.green-rabbit.net.crt"
        nginx['ssl_certificate_key']    = "/etc/gitlab/ssl/gitlab.green-rabbit.net.key"

    ports:
      - '80:80'
      - '443:443'
      - '8022:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
      - ./ssl:/etc/gitlab/ssl
    shm_size: '256m'
